#!/usr/bin/env node
/*
 * Bundle the web client into one self-contained updater.html.
 *
 * Development doesn't need this: index.html loads the ES modules directly, so
 * editing a file and reloading the page is the whole loop. This script exists
 * for people who want a single file they can host anywhere (and for the
 * release artifact) — everything is inlined, so it has no external requests.
 *
 *   node web/tools/build-single.mjs [outfile]
 *
 * esbuild is fetched on demand via npx; it is not a project dependency.
 */

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";

const WEB = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const ESBUILD_VERSION = "0.25.10";
const out = resolve(process.argv[2] ?? join(WEB, "dist", "updater.html"));

/* Bundle the module graph (including the vendored Vue) into one IIFE. */
console.error(`bundling ${join(WEB, "js/main.js")}…`);
const bundle = execFileSync(
  "npx",
  ["--yes", `esbuild@${ESBUILD_VERSION}`, "js/main.js",
   "--bundle", "--format=iife", "--minify", "--platform=browser", "--target=es2022"],
  { cwd: WEB, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 },
);

let html = readFileSync(join(WEB, "index.html"), "utf8");

/* Drop everything that points at a sibling file. A single file has no
 * siblings: the manifest, the icons and (through the manifest link, which is
 * what js/lib/pwa.js tests for) the service worker would all 404. The build is
 * already offline-capable by being one file, so nothing is lost. */
const EXTERNAL_REFS = [
  /[ \t]*<!--[^]*?js\/lib\/pwa\.js[^]*?-->\n?/,          // the comment explaining the link
  /[ \t]*<link rel="manifest"[^>]*>\n?/,
  /[ \t]*<link rel="icon"[^>]*>\n?/,
  /[ \t]*<link rel="apple-touch-icon"[^>]*>\n?/,
];
for (const re of EXTERNAL_REFS) html = html.replace(re, "");

/* Inline every stylesheet in document order, replacing the first <link> with
 * the combined <style> and dropping the rest. */
const links = [...html.matchAll(/[ \t]*<link rel="stylesheet" href="([^"]+)">\n?/g)];
if (links.length === 0) throw new Error("no <link rel=stylesheet> found in index.html");
const css = links
  .map(m => `/* ${m[1]} */\n${readFileSync(join(WEB, m[1]), "utf8").trim()}`)
  .join("\n\n");
html = html.replace(links[0][0], `<style>\n${css}\n</style>\n`);
for (const m of links.slice(1)) html = html.replace(m[0], "");

/* Swap the module entry point for the bundle. `$&`-safe: pass a function so
 * `$` sequences inside minified JS aren't treated as replacement patterns. */
const scriptTag = /[ \t]*<script type="module" src="[^"]+"><\/script>/;
if (!scriptTag.test(html)) throw new Error("no <script type=module> found in index.html");
html = html.replace(scriptTag, () => `<script>\n${bundle.trim()}\n</script>`);

html = html.replace("<head>",
  "<head>\n<!-- Generated by web/tools/build-single.mjs — edit the sources in web/, not this file. -->");

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, html);
console.error(`wrote ${out} (${(Buffer.byteLength(html) / 1024).toFixed(0)} KB)`);
